security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        main:
            pattern: .*
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:  null
                default_target_path: /
                remember_me:    true
            remember_me:
                key:            "%secret%"
                lifetime:       31536000 # 365 jours en secondes
                path:           /
                domain:         ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER
            logout:
                path:           fos_user_security_logout
                target:         /
            anonymous:          true